// All card definitions for Element Forge
const CARDS = {
  // ============ STARTER CARDS (Given to new players) ============
  STARTER: [
    {
      name: "Flame Initiate",
      type: "creature",
      element: "fire",
      attack: 2,
      defense: 1,
      energy_cost: 1,
      rarity: "basic",
      ability: null,
      description: "A novice fire mage learning the basics.",
      is_craftable: false,
      gold_price: 0
    },
    {
      name: "Water Apprentice",
      type: "creature",
      element: "water",
      attack: 1,
      defense: 2,
      energy_cost: 1,
      rarity: "basic",
      ability: null,
      description: "A student of water magic.",
      is_craftable: false,
      gold_price: 0
    },
    {
      name: "Earth Defender",
      type: "creature",
      element: "earth",
      attack: 1,
      defense: 3,
      energy_cost: 2,
      rarity: "basic",
      ability: "taunt",
      description: "Guards the earth with unwavering resolve.",
      is_craftable: false,
      gold_price: 0
    },
    {
      name: "Air Scout",
      type: "creature",
      element: "air",
      attack: 2,
      defense: 1,
      energy_cost: 1,
      rarity: "basic",
      ability: "swift",
      description: "Fast and agile, strikes quickly.",
      is_craftable: false,
      gold_price: 0
    },
    {
      name: "Void Wisp",
      type: "creature",
      element: "void",
      attack: 1,
      defense: 1,
      energy_cost: 1,
      rarity: "basic",
      ability: null,
      description: "A small fragment of the void.",
      is_craftable: false,
      gold_price: 0
    },
    {
      name: "Minor Heal",
      type: "spell",
      element: "water",
      attack: null,
      defense: null,
      energy_cost: 1,
      rarity: "basic",
      ability: "heal_3",
      description: "Restore 3 Life Points.",
      is_craftable: false,
      gold_price: 0
    },
    {
      name: "Spark",
      type: "spell",
      element: "fire",
      attack: null,
      defense: null,
      energy_cost: 1,
      rarity: "basic",
      ability: "damage_2",
      description: "Deal 2 damage to target.",
      is_craftable: false,
      gold_price: 0
    }
  ],

  // ============ COMMON PURCHASABLE CARDS ============
  COMMON: [
    {
      name: "Fire Knight",
      type: "creature",
      element: "fire",
      attack: 4,
      defense: 2,
      energy_cost: 3,
      rarity: "common",
      ability: "burn_1",
      description: "A warrior wreathed in flames.",
      is_craftable: false,
      gold_price: 20
    },
    {
      name: "Frost Mage",
      type: "creature",
      element: "water",
      attack: 2,
      defense: 3,
      energy_cost: 3,
      rarity: "common",
      ability: "freeze_on_hit",
      description: "Freezes enemies with icy touch.",
      is_craftable: false,
      gold_price: 20
    },
    {
      name: "Stone Guardian",
      type: "creature",
      element: "earth",
      attack: 2,
      defense: 5,
      energy_cost: 4,
      rarity: "common",
      ability: "taunt,fortify_1",
      description: "An immovable protector.",
      is_craftable: false,
      gold_price: 20
    },
    {
      name: "Wind Dancer",
      type: "creature",
      element: "air",
      attack: 3,
      defense: 2,
      energy_cost: 2,
      rarity: "common",
      ability: "swift",
      description: "Dances on the wind, striking swiftly.",
      is_craftable: false,
      gold_price: 20
    },
    {
      name: "Shadow Stalker",
      type: "creature",
      element: "void",
      attack: 3,
      defense: 2,
      energy_cost: 3,
      rarity: "common",
      ability: "on_death_discard_1",
      description: "Lurks in shadows, disrupting foes.",
      is_craftable: false,
      gold_price: 20
    },
    {
      name: "Fireball",
      type: "spell",
      element: "fire",
      attack: null,
      defense: null,
      energy_cost: 3,
      rarity: "common",
      ability: "damage_4",
      description: "Deal 4 damage to target.",
      is_craftable: false,
      gold_price: 20
    },
    {
      name: "Healing Wave",
      type: "spell",
      element: "water",
      attack: null,
      defense: null,
      energy_cost: 2,
      rarity: "common",
      ability: "heal_5",
      description: "Restore 5 Life Points.",
      is_craftable: false,
      gold_price: 20
    },
    {
      name: "Gust",
      type: "spell",
      element: "air",
      attack: null,
      defense: null,
      energy_cost: 2,
      rarity: "common",
      ability: "return_creature",
      description: "Return target creature to hand.",
      is_craftable: false,
      gold_price: 20
    },
    {
      name: "Fortify",
      type: "spell",
      element: "earth",
      attack: null,
      defense: null,
      energy_cost: 2,
      rarity: "common",
      ability: "buff_defense_3",
      description: "Give target creature +0/+3.",
      is_craftable: false,
      gold_price: 20
    }
  ],

  // ============ UNCOMMON CARDS ============
  UNCOMMON: [
    {
      name: "Inferno Drake",
      type: "creature",
      element: "fire",
      attack: 5,
      defense: 3,
      energy_cost: 5,
      rarity: "uncommon",
      ability: "burn_2,swift",
      description: "A fierce dragon that burns everything.",
      is_craftable: false,
      gold_price: 50
    },
    {
      name: "Tidal Serpent",
      type: "creature",
      element: "water",
      attack: 3,
      defense: 4,
      energy_cost: 4,
      rarity: "uncommon",
      ability: "flow,on_summon_heal_3",
      description: "Flows with the tide, bringing healing.",
      is_craftable: false,
      gold_price: 50
    },
    {
      name: "Mountain Colossus",
      type: "creature",
      element: "earth",
      attack: 4,
      defense: 6,
      energy_cost: 6,
      rarity: "uncommon",
      ability: "taunt,fortify_2",
      description: "A massive stone giant.",
      is_craftable: false,
      gold_price: 50
    },
    {
      name: "Tempest Spirit",
      type: "creature",
      element: "air",
      attack: 4,
      defense: 2,
      energy_cost: 3,
      rarity: "uncommon",
      ability: "swift,on_summon_draw_1",
      description: "Brings knowledge on the wind.",
      is_craftable: false,
      gold_price: 50
    },
    {
      name: "Void Horror",
      type: "creature",
      element: "void",
      attack: 4,
      defense: 4,
      energy_cost: 5,
      rarity: "uncommon",
      ability: "on_death_banish_random",
      description: "Tears reality when destroyed.",
      is_craftable: false,
      gold_price: 50
    },
    {
      name: "Chain Lightning",
      type: "spell",
      element: "fire",
      attack: null,
      defense: null,
      energy_cost: 4,
      rarity: "uncommon",
      ability: "damage_3_to_3_targets",
      description: "Deal 3 damage to up to 3 targets.",
      is_craftable: false,
      gold_price: 50
    },
    {
      name: "Tsunami",
      type: "spell",
      element: "water",
      attack: null,
      defense: null,
      energy_cost: 5,
      rarity: "uncommon",
      ability: "return_all_enemy_creatures",
      description: "Return all enemy creatures to hand.",
      is_craftable: false,
      gold_price: 50
    }
  ],

  // ============ RARE CARDS ============
  RARE: [
    {
      name: "Phoenix Lord",
      type: "creature",
      element: "fire",
      attack: 6,
      defense: 4,
      energy_cost: 6,
      rarity: "rare",
      ability: "burn_2,resurrect_once",
      description: "Returns from death once with 4/3 stats.",
      is_craftable: false,
      gold_price: 100
    },
    {
      name: "Ocean Sovereign",
      type: "creature",
      element: "water",
      attack: 4,
      defense: 6,
      energy_cost: 6,
      rarity: "rare",
      ability: "taunt,flow,heal_2_per_turn",
      description: "Master of the oceans.",
      is_craftable: false,
      gold_price: 100
    },
    {
      name: "Crystal Golem",
      type: "creature",
      element: "earth",
      attack: 5,
      defense: 7,
      energy_cost: 7,
      rarity: "rare",
      ability: "taunt,fortify_2,ward",
      description: "Nearly indestructible crystal construct.",
      is_craftable: false,
      gold_price: 100
    },
    {
      name: "Storm Dragon",
      type: "creature",
      element: "air",
      attack: 6,
      defense: 4,
      energy_cost: 6,
      rarity: "rare",
      ability: "swift,on_attack_damage_3_random",
      description: "Devastating aerial assault.",
      is_craftable: false,
      gold_price: 100
    },
    {
      name: "Void Reaver",
      type: "creature",
      element: "void",
      attack: 5,
      defense: 5,
      energy_cost: 6,
      rarity: "rare",
      ability: "banish_on_attack",
      description: "Banishes whatever it attacks.",
      is_craftable: false,
      gold_price: 100
    }
  ],

  // ============ CRAFTABLE CARDS - TIER 1 (Basic) ============
  CRAFTABLE_TIER1: [
    {
      name: "Fire Sprite",
      type: "creature",
      element: "fire",
      attack: 3,
      defense: 2,
      energy_cost: 2,
      rarity: "common",
      ability: null,
      description: "A quick striking fire creature.",
      is_craftable: true,
      craft_recipe: { fire: 2 },
      gold_price: null
    },
    {
      name: "Water Spirit",
      type: "creature",
      element: "water",
      attack: 2,
      defense: 3,
      energy_cost: 2,
      rarity: "common",
      ability: null,
      description: "A defensive water creature.",
      is_craftable: true,
      craft_recipe: { water: 2 },
      gold_price: null
    },
    {
      name: "Earth Golem",
      type: "creature",
      element: "earth",
      attack: 2,
      defense: 4,
      energy_cost: 2,
      rarity: "common",
      ability: "taunt",
      description: "A sturdy defensive creature.",
      is_craftable: true,
      craft_recipe: { earth: 2 },
      gold_price: null
    },
    {
      name: "Air Wisp",
      type: "creature",
      element: "air",
      attack: 4,
      defense: 1,
      energy_cost: 2,
      rarity: "common",
      ability: "swift",
      description: "Extremely fast but fragile.",
      is_craftable: true,
      craft_recipe: { air: 2 },
      gold_price: null
    },
    {
      name: "Void Shade",
      type: "creature",
      element: "void",
      attack: 2,
      defense: 2,
      energy_cost: 2,
      rarity: "common",
      ability: "on_death_discard_1",
      description: "Disrupts opponent's hand upon death.",
      is_craftable: true,
      craft_recipe: { void: 2 },
      gold_price: null
    }
  ],

  // ============ CRAFTABLE CARDS - TIER 2 (Advanced) ============
  CRAFTABLE_TIER2: [
    {
      name: "Steam Elemental",
      type: "creature",
      element: "fire",
      attack: 3,
      defense: 3,
      energy_cost: 3,
      rarity: "uncommon",
      ability: "on_summon_heal_2",
      description: "Fire and water create healing steam.",
      is_craftable: true,
      craft_recipe: { fire: 1, water: 1 },
      gold_price: null
    },
    {
      name: "Magma Titan",
      type: "creature",
      element: "fire",
      attack: 5,
      defense: 4,
      energy_cost: 4,
      rarity: "uncommon",
      ability: "on_summon_damage_1_all_enemies",
      description: "Erupts with devastating force.",
      is_craftable: true,
      craft_recipe: { fire: 2, earth: 1 },
      gold_price: null
    },
    {
      name: "Storm Rider",
      type: "creature",
      element: "air",
      attack: 3,
      defense: 2,
      energy_cost: 3,
      rarity: "uncommon",
      ability: "on_summon_draw_1",
      description: "Brings knowledge on storm winds.",
      is_craftable: true,
      craft_recipe: { water: 1, air: 1 },
      gold_price: null
    },
    {
      name: "Dust Devil",
      type: "creature",
      element: "air",
      attack: 2,
      defense: 3,
      energy_cost: 2,
      rarity: "uncommon",
      ability: "swift,fortify_1",
      description: "Whirling sand that grows stronger.",
      is_craftable: true,
      craft_recipe: { earth: 1, air: 1 },
      gold_price: null
    },
    {
      name: "Obsidian Sentinel",
      type: "creature",
      element: "fire",
      attack: 4,
      defense: 3,
      energy_cost: 4,
      rarity: "uncommon",
      ability: "burn_1,on_death_banish_self",
      description: "Volcanic glass forged in the void.",
      is_craftable: true,
      craft_recipe: { fire: 1, void: 1 },
      gold_price: null
    },
    {
      name: "Tidal Guardian",
      type: "creature",
      element: "water",
      attack: 3,
      defense: 5,
      energy_cost: 4,
      rarity: "uncommon",
      ability: "taunt,flow",
      description: "The ocean's protector.",
      is_craftable: true,
      craft_recipe: { water: 2, earth: 1 },
      gold_price: null
    },
    {
      name: "Frost Wraith",
      type: "creature",
      element: "water",
      attack: 2,
      defense: 2,
      energy_cost: 3,
      rarity: "uncommon",
      ability: "on_summon_freeze_1",
      description: "Cold emptiness given form.",
      is_craftable: true,
      craft_recipe: { water: 1, void: 1 },
      gold_price: null
    },
    {
      name: "Granite Crusher",
      type: "creature",
      element: "earth",
      attack: 4,
      defense: 5,
      energy_cost: 5,
      rarity: "uncommon",
      ability: "on_attack_destroy_artifact",
      description: "Stone infused with void energy.",
      is_craftable: true,
      craft_recipe: { earth: 2, void: 1 },
      gold_price: null
    },
    {
      name: "Plasma Dart",
      type: "creature",
      element: "air",
      attack: 3,
      defense: 1,
      energy_cost: 2,
      rarity: "uncommon",
      ability: "swift,ward",
      description: "Intangible and impossibly fast.",
      is_craftable: true,
      craft_recipe: { air: 1, void: 1 },
      gold_price: null
    },
    {
      name: "Wildfire Hawk",
      type: "creature",
      element: "fire",
      attack: 4,
      defense: 2,
      energy_cost: 3,
      rarity: "uncommon",
      ability: "swift,burn_1",
      description: "Spreads flames wherever it flies.",
      is_craftable: true,
      craft_recipe: { fire: 1, air: 1 },
      gold_price: null
    }
  ],

  // ============ CRAFTABLE SPELLS - TIER 3 ============
  CRAFTABLE_TIER3: [
    {
      name: "Lightning Bolt",
      type: "spell",
      element: "air",
      attack: null,
      defense: null,
      energy_cost: 3,
      rarity: "rare",
      ability: "damage_6",
      description: "Raw elemental fury from the sky.",
      is_craftable: true,
      craft_recipe: { air: 2, fire: 1 },
      gold_price: null
    },
    {
      name: "Tidal Surge",
      type: "spell",
      element: "water",
      attack: null,
      defense: null,
      energy_cost: 4,
      rarity: "rare",
      ability: "return_2_enemies",
      description: "Return up to 2 enemy creatures to hand.",
      is_craftable: true,
      craft_recipe: { water: 2, air: 1 },
      gold_price: null
    },
    {
      name: "Meteor Strike",
      type: "spell",
      element: "fire",
      attack: null,
      defense: null,
      energy_cost: 5,
      rarity: "rare",
      ability: "damage_4_all_enemies_2_player",
      description: "Call down the wrath of the heavens.",
      is_craftable: true,
      craft_recipe: { fire: 2, earth: 1 },
      gold_price: null
    },
    {
      name: "Absolute Zero",
      type: "spell",
      element: "water",
      attack: null,
      defense: null,
      energy_cost: 4,
      rarity: "rare",
      ability: "freeze_all_draw_1",
      description: "Freeze all enemies, draw 1 card.",
      is_craftable: true,
      craft_recipe: { water: 2, void: 1 },
      gold_price: null
    },
    {
      name: "Void Rift",
      type: "spell",
      element: "void",
      attack: null,
      defense: null,
      energy_cost: 3,
      rarity: "rare",
      ability: "banish_heal_2",
      description: "Banish target, gain 2 Life.",
      is_craftable: true,
      craft_recipe: { void: 2, air: 1 },
      gold_price: null
    },
    {
      name: "Stone Skin",
      type: "spell",
      element: "earth",
      attack: null,
      defense: null,
      energy_cost: 3,
      rarity: "rare",
      ability: "buff_defense_4_taunt",
      description: "Target creature gains +0/+4 and Taunt.",
      is_craftable: true,
      craft_recipe: { earth: 2, water: 1 },
      gold_price: null
    },
    {
      name: "Inferno",
      type: "spell",
      element: "fire",
      attack: null,
      defense: null,
      energy_cost: 6,
      rarity: "rare",
      ability: "damage_3_all_except_fire",
      description: "Deal 3 damage to all non-Fire creatures.",
      is_craftable: true,
      craft_recipe: { fire: 3, void: 1 },
      gold_price: null
    },
    {
      name: "Nature's Rebirth",
      type: "spell",
      element: "earth",
      attack: null,
      defense: null,
      energy_cost: 5,
      rarity: "rare",
      ability: "resurrect_2_heal_3",
      description: "Return 2 creatures from discard, heal 3.",
      is_craftable: true,
      craft_recipe: { earth: 2, water: 1, air: 1 },
      gold_price: null
    }
  ],

  // ============ CRAFTABLE ARTIFACTS - TIER 4 ============
  CRAFTABLE_TIER4: [
    {
      name: "Prismatic Shard",
      type: "artifact",
      element: "void",
      attack: null,
      defense: null,
      energy_cost: 4,
      rarity: "epic",
      ability: "generate_essence_per_turn",
      description: "Generate 1 random Essence per turn.",
      is_craftable: true,
      craft_recipe: { fire: 1, water: 1, earth: 1, air: 1, void: 1 },
      gold_price: null
    },
    {
      name: "Flame Forge",
      type: "artifact",
      element: "fire",
      attack: null,
      defense: null,
      energy_cost: 4,
      rarity: "epic",
      ability: "fire_cost_minus_1_damage_1_on_summon",
      description: "Fire creatures cost 1 less, deal 1 on summon.",
      is_craftable: true,
      craft_recipe: { fire: 3, earth: 1 },
      gold_price: null
    },
    {
      name: "Tidal Totem",
      type: "artifact",
      element: "water",
      attack: null,
      defense: null,
      energy_cost: 4,
      rarity: "epic",
      ability: "heal_1_per_turn_water_plus_1_defense",
      description: "Heal 1 per turn, Water creatures +0/+1.",
      is_craftable: true,
      craft_recipe: { water: 3, earth: 1 },
      gold_price: null
    },
    {
      name: "Wind Shrine",
      type: "artifact",
      element: "air",
      attack: null,
      defense: null,
      energy_cost: 3,
      rarity: "epic",
      ability: "pay_1_draw_1",
      description: "Pay 1 Energy to draw 1 card per turn.",
      is_craftable: true,
      craft_recipe: { air: 3, water: 1 },
      gold_price: null
    },
    {
      name: "Void Crystal",
      type: "artifact",
      element: "void",
      attack: null,
      defense: null,
      energy_cost: 5,
      rarity: "epic",
      ability: "banish_discard_for_essence",
      description: "Banish from discard for Void Essence.",
      is_craftable: true,
      craft_recipe: { void: 4 },
      gold_price: null
    },
    {
      name: "Mountain Heart",
      type: "artifact",
      element: "earth",
      attack: null,
      defense: null,
      energy_cost: 5,
      rarity: "epic",
      ability: "all_plus_1_1_earth_taunt",
      description: "All creatures +1/+1, Earth has Taunt.",
      is_craftable: true,
      craft_recipe: { earth: 4, fire: 1 },
      gold_price: null
    }
  ],

  // ============ LEGENDARY CRAFTABLES - TIER 5 ============
  CRAFTABLE_LEGENDARY: [
    {
      name: "Phoenix Rebirth",
      type: "spell",
      element: "fire",
      attack: null,
      defense: null,
      energy_cost: 7,
      rarity: "legendary",
      ability: "summon_phoenix_6_6_resurrect",
      description: "Summon 6/6 Phoenix that resurrects once.",
      is_craftable: true,
      craft_recipe: { fire: 4, void: 2 },
      gold_price: null
    },
    {
      name: "Tidal Wave",
      type: "spell",
      element: "water",
      attack: null,
      defense: null,
      energy_cost: 6,
      rarity: "legendary",
      ability: "return_all_enemies_draw_per_return",
      description: "Return all enemies, draw per return.",
      is_craftable: true,
      craft_recipe: { water: 3, air: 2 },
      gold_price: null
    },
    {
      name: "Mountain's Wrath",
      type: "spell",
      element: "earth",
      attack: null,
      defense: null,
      energy_cost: 7,
      rarity: "legendary",
      ability: "damage_half_life_to_all_enemies",
      description: "Deal half your Life as damage to all enemies.",
      is_craftable: true,
      craft_recipe: { earth: 4, fire: 2 },
      gold_price: null
    },
    {
      name: "Void Sovereign",
      type: "creature",
      element: "void",
      attack: 5,
      defense: 5,
      energy_cost: 6,
      rarity: "legendary",
      ability: "banish_per_turn_immune_banish",
      description: "Banish target per turn, immune to Banish.",
      is_craftable: true,
      craft_recipe: { void: 5 },
      gold_price: null
    },
    {
      name: "Elemental Convergence",
      type: "spell",
      element: "void",
      attack: null,
      defense: null,
      energy_cost: 10,
      rarity: "legendary",
      ability: "win_next_turn",
      description: "Win the game at start of next turn.",
      is_craftable: true,
      craft_recipe: { fire: 2, water: 2, earth: 2, air: 2, void: 2 },
      gold_price: null
    },
    {
      name: "Tempest Dragon",
      type: "creature",
      element: "air",
      attack: 7,
      defense: 6,
      energy_cost: 8,
      rarity: "legendary",
      ability: "swift,on_attack_damage_3_divided,ward",
      description: "Master of storm and flame.",
      is_craftable: true,
      craft_recipe: { air: 3, fire: 2, water: 1 },
      gold_price: null
    },
    {
      name: "Eternal Guardian",
      type: "creature",
      element: "earth",
      attack: 4,
      defense: 8,
      energy_cost: 6,
      rarity: "legendary",
      ability: "taunt,fortify_2,heal_2_per_turn",
      description: "Immortal protector that cannot be overcome.",
      is_craftable: true,
      craft_recipe: { earth: 4, water: 2 },
      gold_price: null
    },
    {
      name: "Apocalypse",
      type: "spell",
      element: "void",
      attack: null,
      defense: null,
      energy_cost: 9,
      rarity: "legendary",
      ability: "destroy_all_damage_10_both",
      description: "Destroy all, deal 10 to both players.",
      is_craftable: true,
      craft_recipe: { fire: 3, void: 3 },
      gold_price: null
    }
  ]
};

// Flatten all cards into a single array
const ALL_CARDS = [
  ...CARDS.STARTER,
  ...CARDS.COMMON,
  ...CARDS.UNCOMMON,
  ...CARDS.RARE,
  ...CARDS.CRAFTABLE_TIER1,
  ...CARDS.CRAFTABLE_TIER2,
  ...CARDS.CRAFTABLE_TIER3,
  ...CARDS.CRAFTABLE_TIER4,
  ...CARDS.CRAFTABLE_LEGENDARY
];

module.exports = { CARDS, ALL_CARDS };
